---
kind: pipeline
name: commit
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker build -t quay.io/ukhomeofficedigital/dsa-terragrunt:$${DRONE_COMMIT_SHA} .
  environment:
    # DOCKER_HOST: tcp://172.17.0.1:2375
  when:
    event:
    - pull_request
    - push

- name: docker-push
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+dsa_shared_service" -p=$${DOCKER_TOKEN} quay.io
  - docker tag quay.io/ukhomeofficedigital/dsa-terragrunt:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dsa-terragrun:latest
  - docker push quay.io/ukhomeofficedigital/dsa-terragrunt:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/dsa-terragrunt:latest
  environment:
    # DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  when:
    branch:
    - main
    event:
    - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
